# docker build -f tests_dockerfiles/Dockerfile-3-9 .
FROM python:3.9

RUN apt-get update && apt-get install ffmpeg -y

WORKDIR /tests_dir/

RUN pip install --upgrade pip

COPY requirements.txt /tests_dir
COPY requirements_dev.txt /tests_dir

RUN pip install -r requirements.txt
RUN pip install -r requirements_dev.txt
# RUN pip install noisereduce numpy pytest scipy pydub pytest-xdist scikit-image

COPY audalign /tests_dir/audalign
COPY test_audio /tests_dir/test_audio
COPY tests /tests_dir/tests
COPY pytest.ini /tests_dir

RUN pytest
